version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb+srv://visareadycomp:ya6ataNEiIoaS1Lu@cluster0.f4hyx.mongodb.net/
    volumes:
      - .:/usr/src/app

volumes:
  mongo_data:
